---
objects:
  - name: playdough_test_results
    fields:
      time: timestamp
      org: uuid
      pulse: uuid
      test: uuid
      metrics: map<text,double>
    indices:
      - name: org_pulse_test
        partition:
          - org
          - pulse
          - test
        split:
          column: time
          strategy:
            name: duration
            config:
              duration: P30D
        clustering:
          field: time
          order: DESC
  - name: redstone_defect_stats
    fields:
      time: timeuuid
      high: int
      medium: int
      low: int
    indices:
      - name: time
        partition: []
        split:
          column: time
          strategy:
            name: duration
            config:
              duration: P30D
        clustering:
          field: time
          order: DESC
  - name: series
    fields:
      time: timeuuid
      org: uuid
      pulse: uuid
      test: uuid
      value: double
      event: json
    indices:
      - name: org_pulse_test
        partition:
          - org
          - pulse
          - test
        split:
          column: time
          strategy:
            name: duration
            config:
              duration: P1D
        clustering:
          field: time
          order: DESC
      - name: org_pulse
        partition:
          - org
          - pulse
        split:
          column: time
          strategy:
            name: duration
            config:
              duration: P1D
        clustering:
          field: time
          order: DESC
      - name: org_test
        partition:
          - org
          - test
        split:
          column: time
          strategy:
            name: duration
            config:
              duration: P1D
        clustering:
          field: time
          order: DESC
      - name: org
        partition:
          - org
        split:
          column: time
          strategy:
            name: duration
            config:
              duration: P1D
        clustering:
          field: time
          order: DESC
